name: Semgrep - Scan

on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '0 0 * * 0'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: 🔎 Scan - Semgrep
    
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
